# Generated by Django 4.2.7 on 2025-11-01 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the event', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the event name', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_date', models.DateField(help_text='Date when the event took place')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=300)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the event', null=True, upload_to='event_covers/')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the event is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matches_found', models.IntegerField(default=0, help_text='Number of photos matched')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Event photo file', upload_to='event_photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail version of the photo', null=True, upload_to='event_photos/thumbnails/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Photo caption', max_length=500)),
                ('faces_processed', models.BooleanField(default=False, help_text='Whether face detection has been completed for this photo')),
                ('face_count', models.IntegerField(default=0, help_text='Number of faces detected in this photo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoding', models.TextField(help_text='Face encoding data (128-dimension vector stored as text)')),
                ('top', models.IntegerField(help_text='Top coordinate of face bounding box')),
                ('right', models.IntegerField(help_text='Right coordinate of face bounding box')),
                ('bottom', models.IntegerField(help_text='Bottom coordinate of face bounding box')),
                ('left', models.IntegerField(help_text='Left coordinate of face bounding box')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(help_text='Photo this face encoding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='events.photo')),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', '-uploaded_at'], name='events_phot_event_i_407a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['faces_processed'], name='events_phot_faces_p_45f04f_idx'),
        ),
        migrations.AddIndex(
            model_name='faceencoding',
            index=models.Index(fields=['photo'], name='events_face_photo_i_8d3289_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-event_date'], name='events_even_event_d_b32ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
    ]
